# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twit',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='twit',
            name='createdOn',
        ),
        migrations.AddField(
            model_name='twit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
