# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-15 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0004_auto_20170615_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
